
configuration:
  - Release

install:
  - cinst --allow-empty-checksums smlnj

before_build:
  - set PATH=%PATH%;C:\Program Files (x86)\SMLNJ\bin

build_script:
  - repoint install
  - ps: ext\sml-buildscripts\smlrun.ps1 test\tests.mlb
  

