dist:
  - xenial

language:
  - cpp

sudo:
  - false

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - mlton
      - smlnj
      - libsmlnj-smlnj

before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then brew update ; brew install mlton polyml ; fi
      
script:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then make ; fi
  - make release
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]] ; then ./ext/sml-buildscripts/smlrun test/tests.mlb ; fi

